language: java

sudo: false

jdk:
  - oraclejdk8

script: .travis/script.sh

after_success: .travis/after_success.sh

deploy:
  provider: releases
  api_key:
    secure: fZhXes6tgb1SgKnAfwuOfhkeTbLcC3/JaIunn9rwYfBFqxHsYI7z1oyaIF+atygK5S3cemzMeFXpYOhuKUZPf0s58YHTdkzeEuXIbU1/9XAXiEiL2neGtJg1uB9Go93i7s9SChY4wceC8WHnJJXqCuqrz0blOKXgkxB+IcBjpfDUCTao2WIsn0fDFtzAUhbBhgS2/TVwYkBqaglvQeygZtac89qeTaREoDcWQhPIknuQ/JZAIOpzE4gt7JGfySHCZLCJ9JA/tA4RpWWy5VtG1tsTZSQ2IVAwq0unm94zRp/j4GWZ5OcUmFvidQdko71ph4ytyDaCWf9XG0/THdKHlnmdHan6Z7bWTc/DqI2Ovt9+2FMzZU63GJP0RCkheQLhecxMV2NqY5ORlzslIIM1EzWpk+3ua/ZCxl8SWVKQq0oQ8ujGiaydvTTVLuerjKQUjotfO7njl6FNNpxRhXArD/1AI2amRxifosou3o0/1dX7icU/H+JetHmgLWyujvc13kEyxGu0naafsDz4wxuTpHbA26safSmct9qbJDpaBBEzdK0n83vAhzAqAYBEJV9TQFUNlzH1qcl1SWR4pssZCPqqOROxDSodW2b0tS52L7Y7mqXwsNKPtyzpa4WNF1cCKGqMposRi0r+tpJE5e3UprF66Mde53cFUTS9Hq+jHO4=
  file:
    - build/distributions/packt4free-${TRAVIS_TAG}.tar
    - build/distributions/packt4free-${TRAVIS_TAG}.zip
  skip_cleanup: true
  on:
    repo: madhead/packt4free
    tags: true
